[package]
name = "pinyin"
version = "0.0.6"
authors = ["mozillazg <mozillazg101@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/mozillazg/rust-pinyin"
repository = "https://github.com/mozillazg/rust-pinyin"
description = "Convert Chinese to pinyin"
documentation = "http://mozillazg.com/rust-pinyin/"
keywords = ["pinyin", "hanzi", "Chinese"]
build = "build.rs"

[features]
unstable = []

[dependencies]
phf = "~0.7.3"

[build-dependencies]
phf_codegen = "~0.7.3"
